"""empty message

Revision ID: 116ed1073790
Revises: 460a3a41e37a
Create Date: 2014-08-06 19:29:41.005280

"""

# revision identifiers, used by Alembic.
revision = '116ed1073790'
down_revision = '460a3a41e37a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    ### end Alembic commands ###
