"""empty message

Revision ID: 12084a388255
Revises: 9aaae9f4695
Create Date: 2014-08-09 17:50:33.923884

"""

# revision identifiers, used by Alembic.
revision = '12084a388255'
down_revision = '9aaae9f4695'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('like', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'like')
    ### end Alembic commands ###
