"""empty message

Revision ID: 160cf757d84
Revises: c462d934b91
Create Date: 2014-08-09 16:45:27.850831

"""

# revision identifiers, used by Alembic.
revision = '160cf757d84'
down_revision = 'c462d934b91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
