"""empty message

Revision ID: 1e196e33585f
Revises: 160cf757d84
Create Date: 2014-08-09 17:02:58.309716

"""

# revision identifiers, used by Alembic.
revision = '1e196e33585f'
down_revision = '160cf757d84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
