"""empty message

Revision ID: 460a3a41e37a
Revises: None
Create Date: 2014-08-06 18:52:18.660810

"""

# revision identifiers, used by Alembic.
revision = '460a3a41e37a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
