"""empty message

Revision ID: 54ea273b6525
Revises: 12084a388255
Create Date: 2014-08-09 18:26:14.450919

"""

# revision identifiers, used by Alembic.
revision = '54ea273b6525'
down_revision = '12084a388255'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
