"""empty message

Revision ID: 9aaae9f4695
Revises: 1e196e33585f
Create Date: 2014-08-09 17:14:25.029320

"""

# revision identifiers, used by Alembic.
revision = '9aaae9f4695'
down_revision = '1e196e33585f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
