"""empty message

Revision ID: c462d934b91
Revises: 5214a4a94221
Create Date: 2014-08-09 16:36:09.987110

"""

# revision identifiers, used by Alembic.
revision = 'c462d934b91'
down_revision = '5214a4a94221'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
